### ISSUE TITLE
Chrome driver and work?

### ISSUE THREAD

**Issue by rogercorrea** [raju249/InstaBot#1]
Hi!
The script work?
What the is "chrome driver"?

Thanks for use Python!

**Comment by rogercorrea** [comment]
I found about Chrome driver and I installed.
But don't understand the line 5 and 6.

"INSTA_LOGIN_URL" is actually Instagram login page?
What the is "USERNAME_AND_PASSWORD_DICT"?

Thanks!

**Comment by rogercorrea** [comment]
I found one error after of the configured data.py file:

Traceback (most recent call last):
  File "main.py", line 92, in <module>
    main(user)
  File "main.py", line 74, in main
    login_user(user,USERNAME_AND_PASSWORD_DICT[user])
  File "main.py", line 39, in login_user
    login_form = find_login_form()
  File "main.py", line 21, in find_login_form
    return driver.find_element_by_class_name("_rwf8p")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 413, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"class name","selector":"_rwf8p"}
  (Session info: chrome=51.0.2704.106)
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.16.0-4-amd64 x86_64)

**Comment by raju249** [comment]
Hi @rogercorrea 
`USERNAME_AND_PASSWORD_DICT` are the usernames and password I used to login and follow any given account.
This usernames and passwords are users who follow any given user.
This dictionary is in `data.py` file which I  didn't upload since it had user confidential data.
One way of creating this dictionary is you can create fake usernames and fake passwords for adding followers to your account
Thanks!
I hope this helps.
Reply here for any information
